name: build
on: push
jobs:
#  build-14:
#    runs-on: ubuntu-22.04
#    steps:
#      - uses: actions/checkout@v1
#      - run: sudo apt-get install build-essential llvm-14 llvm-14-dev clang-14 libedit-dev
#      - run: cmake -DLLVM_CONFIG=/usr/bin/llvm-config-14 . && make && make tests
#  build-win-14:
#    runs-on: windows-latest
#    steps:
#      - name: Install winget
#        uses: Cyberboss/install-winget@v1
#      - uses: actions/checkout@v1
#      - run: winget install -e --id Kitware.CMake --disable-interactivity --accept-source-agreements
  build-macos-14:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - run: brew install llvm@14 #llvm-dev
      - run: brew link llvm@14
      - run: ls -lah /usr/local/Cellar/
      - run: ls -lah /usr/local/Cellar/llvm@14
      - run: ls -lah /usr/local/Cellar/llvm@14/14.0.6/
      - run: ls -lah /usr/local/Cellar/llvm@14/14.0.6/bin
      - run: ls -lah /usr/local/opt/llvm/bin/
      - run: which llvm-config
      - run: which llvm-config-14
      - run: cmake . -DLLVM_CONFIG=/usr/local/opt/llvm/bin/llvm-config && make -j$(nproc) && make tests
