name: build
on: push
jobs:
#  build-14:
#    runs-on: ubuntu-22.04
#    steps:
#      - uses: actions/checkout@v1
#      - run: sudo apt-get install build-essential llvm-14 llvm-14-dev clang-14 libedit-dev
#      - run: cmake -DLLVM_CONFIG=/usr/bin/llvm-config-14 . && make && make tests

#workaround to remove log output from "spinner"
#https://gist.github.com/asheroto/96bcabe428e8ad134ef204573810041f
#also see
#https://github.com/microsoft/winget-cli/issues/3494
  build-win-14:
    runs-on: windows-latest
    steps:
      - run: Invoke-WebRequest -Uri https://codeload.github.com/llvm/llvm-project/tar.gz/refs/tags/llvmorg-14.0.6 -OutFile llvm-project.tar.gz
      - run: pwd
      - run: ls
      - run: mkdir llvm-project
      - run: tar -xf llvm-project.tar.gz -C llvm-project
      - run: pwd
      - run: ls
      - run: cd llvm-project
      - run: pwd
      - run: ls
      - run: mv ./*/* ./
      - run: pwd
      - run: ls
      - run: cmake -S llvm -B build -G "Visual Studio 16 2019" -A x64 -DLLVM_ENABLE_PROJECTS='clang' -DCMAKE_BUILD_TYPE=Release
      - run: pwd
      - run: ls
      - uses: Cyberboss/install-winget@v1
      - uses: actions/checkout@v1
      - run: winget install -e --id Kitware.CMake --disable-interactivity --accept-source-agreements
      - run: cmake .
#  build-macos-14:
#    runs-on: macos-latest
#    steps:
#      - uses: actions/checkout@v1
#      - run: brew install llvm@14
#      - run: PATH="/usr/local/opt/llvm@14/bin:$PATH" cmake . && make -j$(nproc) && make tests
