name: build
on: workflow_dispatch #[push, pull_request]
jobs:
#  macos-build-dale-and-llvm-14:
#    runs-on: macos-latest
#    steps:
#      - uses: actions/checkout@v4
#        with:
#          repository: llvm/llvm-project
#          ref: llvmorg-14.0.6
#          path: llvm-project
#          clean: false
#      - run: |
#          cd llvm-project
#          cmake . -G Ninja
#          ninja
#      - uses: actions/checkout@v4
#      - run: cmake -DLLVM_CONFIG=../llvm-project/bin/llvm-config . && make -j$(nproc) && make tests
  build-win-14:
    #https://github.com/actions/runner-images/blob/main/images/windows/Windows2019-Readme.md
    runs-on: windows-2019
    steps:
      - uses: actions/cache/restore@v4
        id: vcpkg-cache
        with:
          path: C:\vcpkg
          key: vcpkg-cache
      - if: steps.vcpkg-cache.outputs.cache-hit != 'true'
        run: vcpkg install pkgconf libffi
      - if: steps.vcpkg-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: C:\vcpkg
          key: vcpkg-cache
      #https://github.com/llvm/actions/blob/main/setup-windows/vs_setup.bat
      - name: llvm setup windows
        uses: llvm/actions/setup-windows@main
        with:
          arch: amd64
      - uses: actions/checkout@v4
        with:
          repository: llvm/llvm-project
          ref: llvmorg-14.0.6
          path: D:/a/dale/dale/llvm-project
          clean: false
      - uses: actions/cache/restore@v4
        id: cache
        with:
          path: D:/a/dale/dale/llvm-build
          key: llvm-build2
        #-DLLVM_TARGETS_TO_BUILD=X86 -Thost=x64
      - if: steps.cache.outputs.cache-hit != 'true'
        name: populate llvm-build if not cached
        run: |
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_PROJECTS='clang' -S D:/a/dale/dale/llvm-project/llvm/ -B D:/a/dale/dale/llvm-build
          cd D:/a/dale/dale/llvm-build
          ninja
      - if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: D:/a/dale/dale/llvm-build
          key: llvm-build2
      - uses: actions/checkout@v4
        with:
          path: D:/a/dale/dale/dale
      - run: cmake -DCMAKE_TOOLCHAIN_FILE="C:/vcpkg/scripts/buildsystems/vcpkg.cmake" -DLLVM_CONFIG="D:/a/dale/dale/llvm-build/bin/llvm-config.exe" -G Ninja -S dale -B "D:/a/dale/dale/dale-build"
      - run: $env:path
      - run: |
          cd "D:/a/dale/dale/dale-build"
          ninja
      - run: |
          cd "D:/a/dale/dale/dale-build"
          ninja -j 1
