name: build
on: push
jobs:
#  build-14:
#    runs-on: ubuntu-22.04
#    steps:
#      - uses: actions/checkout@v1
#      - run: sudo apt-get install build-essential llvm-14 llvm-14-dev clang-14 libedit-dev
#      - run: cmake -DLLVM_CONFIG=/usr/bin/llvm-config-14 . && make && make tests

#workaround to remove log output from "spinner"
#https://gist.github.com/asheroto/96bcabe428e8ad134ef204573810041f
#also see
#https://github.com/microsoft/winget-cli/issues/3494
  build-win-14:
    #https://github.com/actions/runner-images/blob/main/images/windows/Windows2019-Readme.md
    runs-on: windows-2019
    steps:
      #https://github.com/llvm/actions/blob/main/setup-windows/vs_setup.bat
      - name: llvm setup windows
        uses: llvm/actions/setup-windows@main
        with:
          arch: amd64
#      - name: microsoft setup msbuild
#        uses: microsoft/setup-msbuild@v2
      - uses: actions/cache/restore@v4
        id: cache
        with:
          path: llvm-bin
          key: ${{ runner.os }}
      - uses: actions/checkout@v4
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          repository: llvm/llvm-project
          ref: llvmorg-14.0.6
          path: llvm-project
          clean: false
          sparse-checkout: llvm
      - run: pwd
      - run: ls
      - name: populate llvm if not cached
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_PROJECTS='clang' -S .\llvm-project\llvm\ -B llvm-build
          cd llvm-build
          ninja
          cp -a llvm-build/bin llvm-bin
      - uses: actions/cache/save@v4
        if: always()
        with:
          path: llvm-bin
          key: ${{ runner.os }}
      - uses: actions/checkout@v4
      - run: pwd
      - run: ls
      - run: D:/a/dale/llvm-bin/llvm-config.exe --version
      - run: cmake -DLLVM_CONFIG="D:/a/dale/llvm-bin/llvm-config.exe" -G Ninja .
#  build-macos-14:
#    runs-on: macos-latest
#    steps:
#      - uses: actions/checkout@v1
#      - run: brew install llvm@14
#      - run: PATH="/usr/local/opt/llvm@14/bin:$PATH" cmake . && make -j$(nproc) && make tests
